### ISSUE TITLE
[SDK 2013 MP / Windows] Dedicated server won't start anymore with MM v1.12 git-1166

### ISSUE THREAD

**Issue by JoelTroch** [alliedmodders/metamod-source#101]
Game/version: Zombie Panic! Source v3.2.6
Engine branch: Source SDK 2013 Multiplayer
Dedicated server AppID: 17505
Platform: Windows

Starting a Zombie Panic! Source dedicated server with Metamod: Source v1.12 git-1166 is no longer possible and causes an engine error popup to appear with the text: "`NUM_FOR_EDICT: bad pointer`".

A community server operator sent me crash dumps and the call stack is pointing [here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/entitylist_base.cpp#L225) when the game rules class is creating the `team_manager` entities.

This issue cannot be reproduced with build 1165 and lower. Tested both with and without a SourceMod installation.

**Comment by JoelTroch** [comment]
Update: looks like No More Room in Hell 1.13.2 (dedicated server AppID 317670) is also impacted (running on Source SDK 2013 Multiplayer too)

**Comment by psychonic** [comment]
Do you happen to know what previous version of MM:S you were on that was working properly?

**Comment by JoelTroch** [comment]
> Do you happen to know what previous version of MM:S you were on that was working properly?

Quoting what I said above:

> This issue cannot be reproduced with build 1165 and lower. Tested both with and without a SourceMod installation.

**Comment by psychonic** [comment]
Sorry, missed that when reading. It's surely related to that change. I'll look into it.

Thanks for reporting
