### ISSUE TITLE
TF2 server stuck on loading with Metamod Source

### ISSUE THREAD

**Issue by leeyangyik** [alliedmodders/metamod-source#110]
I tried to start up my TF2 server, but it gets stuck on this screen no matter what I do.

The server starts fine if I load it without Metamod.

![Metamod issue](https://github.com/alliedmodders/metamod-source/assets/136493717/7df32816-532d-4a5d-8109-944dccf8a36b)

**Comment by peace-maker** [comment]
Which metamod version are you using exactly? Do you have any metamod plugins installed like sourcemod?

**Comment by peace-maker** [comment]
Can you try without any metamod plugins to see if the problem is really with metamod or some other plugin, please?

**Comment by leeyangyik** [comment]
> Can you try without any metamod plugins to see if the problem is really with metamod or some other plugin, please?

I just tried loading the server with Metamod but without SourceMod, and have confirmed the SourceMod is likely the cause of my server not starting.

**Comment by asherkin** [comment]
We don't use GitHub as a support channel (the SM repo makes that clearer as it's higher traffic), you should come on over to the AM forum or Discord for help troubleshooting.
