### ISSUE TITLE
Metamod won't load "addons/metamod/bin/win64/server"

### ISSUE THREAD

**Issue by TheRjavisDev** [alliedmodders/metamod-source#111]
I'm asking for my friend by the way

[console_text.txt](https://github.com/alliedmodders/metamod-source/files/11859831/console_text.txt)
[server.cfg](https://cdn.discordapp.com/attachments/1120778385057140777/1122191284925378560/server.cfg)
[start.bat](https://cdn.discordapp.com/attachments/1120778385057140777/1122191234660843571/start.bat)

**Comment by TheRjavisDev** [comment]
confirmed that the same happens to my server
*it boots tho*

**Comment by anigpon** [comment]
Yeah
