### ISSUE TITLE
A bit lost on setting this up with CSS listenserver

### ISSUE THREAD

**Issue by Shaddox** [alliedmodders/metamod-source#113]
Good  afternoon!

I'm trying to get this running on my PopOS 22.04 (x64)  installation to play CSS on a listenserver. CSS is the current latest steam version.  However, I currently have no idea how to move things along due to this error in the logs: 

```
L 08/26/2023 - 03:22:22: Detected engine 5 but could not load: libvstdlib_srv.so: cannot open shared object file: No such file or directory
```

I have installed the 32 bit dependencies as listed in the documentation and it doesn't seem to help. Is there anything else I should be doing? I tried with both the latest stable and the latest downloadable dev build.

Thank you!

**Comment by psychonic** [comment]
Listen servers are not currently supported
