### ISSUE TITLE
CS2 1233

### ISSUE THREAD

**Issue by asdfxD** [alliedmodders/metamod-source#136]
Hi,

Metamod DEV 1232, 1233 is not working in cs2 "Linux" why? 1225 still works.

**Comment by stefanobieler** [comment]
what issue are you running into? I'm also having trouble compiling for cs2. but not sure if it's just because i'm a noob to this project and doing something wrong? or if it is indeed broken right now for cs2 compilation?

**Comment by psychonic** [comment]
While it's possible that there were a span of builds with a loading issue, I cannot reproduce this problem using the current latest available, 2.0.1256.

If you need installation assistance, please use the Alliedmodders forum or Discord
