### ISSUE TITLE
not working with 64-bit css dedicated srv

### ISSUE THREAD

**Issue by denz8028** [alliedmodders/metamod-source#139]
trying to load mm:s on nillerusr/source-engine but mm:s not loading with wrong elf class 32 bits
metamod-fatal.log:
<code>L 10/15/2023 - 14:09:35: Detected engine 5 but could not load: /home/r00t/cssds/usr/local/cstrike/addons/metamod/bin/linux64/metamod.2.css.so: cannot open shared object file: No such file or directory
L 10/15/2023 - 14:10:00: Detected engine 5 but could not load: /home/r00t/cssds/usr/local/cstrike/addons/metamod/bin/linux64/metamod.2.css.so: cannot open shared object file: No such file or directory
L 10/15/2023 - 14:10:56: Detected engine 5 but could not load: /home/r00t/cssds/usr/local/cstrike/addons/metamod/bin/linux64/metamod.2.css.so: cannot open shared object file: No such file or directory
L 10/15/2023 - 14:12:00: Detected engine 5 but could not load: /home/r00t/cssds/usr/local/cstrike/addons/metamod/bin/linux64/metamod.2.css.so: wrong ELF class: ELFCLASS32
</code>

**Comment by psychonic** [comment]
For CS:S, we only support the official dedicated server build, which is only available as 32-bit binaries.
