### ISSUE TITLE
MMS: Fatal error: Detected engine 25 but could not load - Military Conflict Vietnam

### ISSUE THREAD

**Issue by sapphonie** [alliedmodders/metamod-source#144]
MMS: Fatal error: Detected engine 25 but could not load: /home/sappho/mcvTEST/mcv/vietnam/addons/metamod/bin/linux64/metamod.2.mcv.so: undefined symbol: g_pCVar

Tried with latest versions of MMS 1.12 and 2.x, same results

> psychonic — Today at 8:44 AM
I'm guessing it's probably an issue with the build manifest. Make an issue or poke me again in a few days. Currently away

**Comment by PlayBoy31** [comment]
Linked to https://github.com/alliedmodders/metamod-source/issues/146

**Comment by psychonic** [comment]
Fix is here, https://github.com/alliedmodders/hl2sdk-manifests/commit/98090552ca1fe28c5e1d547b42ef71855e236768. I _believe_ that the next MM:S build will pick it up.

**Comment by psychonic** [comment]
There is a new build running now. 2.0.1257 and later should be alright.
