### ISSUE TITLE
MMS: Fatal error: Detected engine 17 (+21 and 25) but could not load - Fistful of Frags, Pirates and Vikings and Knights II and Black Mesa

### ISSUE THREAD

**Issue by PlayBoy31** [alliedmodders/metamod-source#146]
**For Fistful of Frags:**
`Detected engine 17 but could not load: /servers/fof_ds/fof/../fof/addons/metamod/bin/metamod.2.sdk2013.so: undefined symbol: __pow_finite`

**For Pirates, Vikings and Knights II:**
`Detected engine 24 but could not load: /servers/pvkii_ds/pvkii/../pvkii/addons/metamod/bin/metamod.2.pvkii.so: undefined symbol: __pow_finite`

**For Black Mesa:**
`Detected engine 21 but could not load: /servers/bms_ds/bms/addons/metamod/bin/metamod.2.bms.so: undefined symbol: __pow_finite`

**With:**
SourceMod Version: 1.12.0.7071
Metamod:Source version 2.0.0-dev+1255
Debian 12.2 up to date

**Have a look at:**
https://reviews.llvm.org/D74712

**Comment by PlayBoy31** [comment]
**Root cause:**
The *_finite calls have been removed on lib math (see https://reviews.llvm.org/D74712)

Temp fix for those who want to build it for those games until its fixed propoerly:

_create a file mymath.c_

```
#include <math.h>

double __pow_finite(double x, double y);

double __pow_finite(double x, double y)
{
   return pow(x, y);
}
```

_Compile it and create the lib:_
```
gcc -m32 -c mymath.c
ar rcs libmymath.a mymath.o
```

Link your metamod build with this library

**Comment by psychonic** [comment]
Thanks. It seems this affects any game/mod that's compiled against libm from the Scout version of the Steam Runtime

**Comment by dvander** [comment]
This is supposed to be fixed in the build by linking in https://github.com/alliedmodders/amtl/blob/master/compat/stdcxx.cpp

**Comment by dvander** [comment]
Oh, we never actually do that. That'd be why.
