### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by metacop** [alliedmodders/metamod-source#157]
It gives me an error that it cannot find a ++ compiler, but I already have visual studio 2022 installed, install minGW. and it doesn't take the compiler. Is there a way to tell python to send it the compiler path or something.

 follow these steps from the official website

https://cs2.poggu.me/metamod/compilation/windows#installing-visual-studio-2022

![image](https://github.com/alliedmodders/metamod-source/assets/56640826/4baaa7ef-150f-48bc-9991-b6f993f82bcd)

![image](https://github.com/alliedmodders/metamod-source/assets/56640826/bf39727e-5cf3-4662-8b53-91269d65bfd3)

**Comment by psychonic** [comment]
The MSVC tools need to be in your `PATH`. The easiest way to do that is to use the "Developer command prompt" shortcut that comes with Visual Studio. MinGW is not supported either, as it has a different ABI than MSVC, and compatibility with Valve's binaries is required.

**Comment by metacop** [comment]
> The MSVC tools need to be in your `PATH`. The easiest way to do that is to use the "Developer command prompt" shortcut that comes with Visual Studio. MinGW is not supported either, as it has a different ABI than MSVC, and compatibility with Valve's binaries is required.
![image](https://github.com/alliedmodders/metamod-source/assets/56640826/1eab89d4-4b95-4060-ab3c-31d02dfac537)

I tried all the visual code 2022 warnings and the error is the same. Can you make an example or help me and not close the post, because there is still no solution to my problem
