### ISSUE TITLE
Important file(s) missing/renamed required for Metamod to run on TF2 (Linux)

### ISSUE THREAD

**Issue by The-Blue-Sans-Group** [alliedmodders/metamod-source#160]
ive been trying to run the current stable release (as of today) of metamod for linux on my latest version of tf2 (as of today) on my linux mint 21.2 cinnamon pc and it isnt working, no matter how i try, it always fails to start metamod with the same error listed below, im not sure if there are more files that are missing (and/or renamed) that are required, either, so i was wondering if you all could check on this.

> L 01/18/2024 - 17:23:51: Detected engine 15 but could not load: libvstdlib_srv.so: cannot open shared object file: No such file or directory

**Comment by psychonic** [comment]
Metamod:Source is only supported on dedicated servers. Running with a client install of games (including TF2) is not supported.
