### ISSUE TITLE
Metamod broken on cs2?

### ISSUE THREAD

**Issue by himenekocn** [alliedmodders/metamod-source#163]
Is the Metamod on CS2 broken?

**Comment by Porcellacion** [comment]
Yup, seems like it broke after tonights update

**Comment by lostsoul6** [comment]
when should we expect a fix? CS# also broken

**Comment by Kirzilla** [comment]
Yep, broken after tonight update
```
MMS: Fatal error: Detected engine 26 but could not load: /home/cs2server/serverfiles/game/csgo/addons/metamod/bin/linuxsteamrt64/metamod.2.cs2.so: undefined symbol: _ZN9KeyValues9GetStringEPKcS1_Pcm
```

**Comment by denrio157** [comment]
Me too, something wrong with me? I'm running on Windows Server 2022
![image](https://github.com/alliedmodders/metamod-source/assets/31591836/064d7bb4-0de5-4ffe-9632-d8c1280ccb99)

**Comment by andre1886** [comment]
он не сломался, просто он не поддерживает новый build 1.39.8.7 cs2. будем ждать тестировать.

**Comment by andre1886** [comment]
Спасибо парни все работает, вы супер.
