### ISSUE TITLE
mm_basedir Not Working in CS2

### ISSUE THREAD

**Issue by LianZiZhou** [alliedmodders/metamod-source#166]
Setting +mm_basedir "addons/metamod_ac" has no effect in CS2.
```
mm_basedir
Unknown command 'mm_basedir'!
meta alias
Alias      File
 ---
counterst  addons/counterstrikesharp/bin/win64/counterstrikesharp
 ---
1 aliases total.
```
I modified the vdf of counterstrikesharp in addons/metamod_ac, the expected behavior is to load addons/counterstrikesharp_ac/bin/win64/counterstrikesharp.
counterstrikesharp.vdf in addons/metamod_ac
```
"Metamod Plugin"
{
	"alias"	"counterstrikesharp"
	"file"	"addons/counterstrikesharp_ac/bin/win64/counterstrikesharp"
}
```

**Comment by psychonic** [comment]
ConVars in MM:S (including `mm_basedir`) are known to not function at the moment in Source 2 games until https://github.com/alliedmodders/metamod-source/pull/135 is finished.

**Comment by GAMMACASE** [comment]
These convars should now be available for use in s2 titles.
