### ISSUE TITLE
incorrect link to build instructions

### ISSUE THREAD

**Issue by tschumann** [alliedmodders/metamod-source#171]
I was trying to build from source and README.md links to https://wiki.alliedmods.net/Building_SourceMod which isn't quite right - Metamod Source does have a checkout-deps.sh file which seems fairly similar but the path is different.

If I were to update that, what's better - new wiki article? Or instructions in README.md?

For anyone searching for build instructions, this is what I did:
```
cd ..
metamod-source/support/checkout-deps.sh -s episode1
```
And then the ambuild stuff from the above link.

**Comment by psychonic** [comment]
I think a README.md would be great.

**Comment by tschumann** [comment]
Thanks - hopefully https://github.com/alliedmodders/metamod-source/pull/172 covers it.
