### ISSUE TITLE
Dota 2 error with Metamod 2.0

### ISSUE THREAD

**Issue by Greelan** [alliedmodders/metamod-source#190]
When running the Dota 2 server on Linux with Metamod 2.0 (tried various builds like 1313 and 1225), I get:

`MMS: Fatal error: Detected engine 12 but could not load: /AMP/dota2/570/game/dota/addons/metamod/bin/linuxsteamrt64/metamod.2.dota.so: undefined symbol: _AssertValidReadPtr
`

Any thoughts?

**Comment by psychonic** [comment]
The dota branch of the hl2sdk repo is currently a bit out of date due to no one actively maintaining it.

**Comment by Greelan** [comment]
OK, thanks for the response
