### ISSUE TITLE
[Issue] MM not loading for CS2 after The Armory update (2 October 2024)

### ISSUE THREAD

**Issue by Ston3Cold** [alliedmodders/metamod-source#193]
Hi there,

Valve released an update for CS2 on 2 October (The Armory). As part of the update quite several things have been changed in the game engine-wise, and as such has caused MM not to load correctly anymore. For example, when trying to boot my dedicated servers, I'm greeted with this error message:

![mmcs2error](https://github.com/user-attachments/assets/b756f93e-a668-4aa2-a004-c51d197bccc3)

Any estimation as to how long it would take to make MM compatible with the latest CS2 update? 

Thanks in advance,
SC

**Comment by igorgusarov** [comment]
Same issue on a Linux server:
```MMS: Fatal error: Detected engine 26 but could not load: /home/ubuntu/cs2/game/csgo/addons/metamod/bin/linuxsteamrt64/metamod.2.cs2.so: undefined symbol: _AssertValidWritePtr```

**Comment by bigcarsd** [comment]
same problem on linux
`MMS: Fatal error: Detected engine 26 but could not load: /home/steam/cs2-dedicated/game/csgo/addons/metamod/bin/linuxsteamrt64/metamod.2.cs2.so: undefined symbol: _AssertValidWritePtr`

**Comment by bili12685** [comment]
same problem on debian11.1 server
MMS: Fatal error: Detected engine 26 but could not load: /home/cs2/game/csgo/addons/metamod/bin/linuxsteamrt64/metamod.2.cs2.so: undefined symbol: _AssertValidWritePtr

**Comment by bili12685** [comment]
same problem on debian11.1 server

MMS: Fatal error: Detected engine 26 but could not load: /home/cs2/game/csgo/addons/metamod/bin/linuxsteamrt64/metamod.2.cs2.so: undefined symbol: _AssertValidWritePtr

**Comment by bili12685** [comment]
> [metamod.zip](https://github.com/user-attachments/files/17243525/metamod.zip)

thanks bro it can work

**Comment by DiDHack** [comment]
> [metamod.zip](https://github.com/user-attachments/files/17243525/metamod.zip)

Hello! What exactly did you changed? The same errors in the plugins

**Comment by Gawnz1** [comment]
Debian 12, same issue: `_AssertValidWritePtr`. 

Tested the above ZIP by @exababy, it loads okay, not sure if SDK should be updated to support existing metamod plugins.
Do a PR if everything is okay.

**Comment by Gawnz1** [comment]
@DiDHack,

> Hello! What exactly did you changed? The same errors in the plugins

The first problem is from the metamod itself, which is giving this `_AssertValidWritePtr` error. After using the @exababy's zip, the error is not there and metamod loads okay.

When trying to load a **PLUGIN (!)**, there is this error: `AssertValidStringPtr`, which is from SDK, maybe SDK needs to be updated too.

**Comment by Ston3Cold** [comment]
> [metamod.zip](https://github.com/user-attachments/files/17243525/metamod.zip)

Any chance that you could perhaps post a Windows variant too, please? I don't do Linux :(

**Comment by DiDHack** [comment]
@Gawnz1 I understand. I just want to understand what changed to implement this changes to my plugin or SDK

**Comment by Ston3Cold** [comment]
> you need to build the plugins yourself, if you need sdk you can find it here.
> 
> https://github.com/exababy/hl2sdk

I assume this was directed towards me? You have to excuse me, but I have no prior knowledge of using the sdk to build the plugins. If you could just break down the steps for me, I'll attempt it as I have Visual Studio 2022 installed.

**Comment by 0x132406C** [comment]
> [metamod.zip](https://github.com/user-attachments/files/17243525/metamod.zip)

bro,just windows

**Comment by DiDHack** [comment]
@exababy did you do something else except comment the strings AssertValid...? Thank You!

**Comment by Coffimix** [comment]
What is the fix?

**Comment by moises4863** [comment]
Hi, same issue happen on my host 
![image](https://github.com/user-attachments/assets/eb8af05b-59ad-4878-990f-5daae24e15f3)

**Comment by fpaezf** [comment]
Can anyone upload the Windows version please?

**Comment by mayersgamer** [comment]
> Can anyone upload the Windows version please?

just wait for the offcial , that one is full of bugs and crash and errors

**Comment by raszyniaczek** [comment]
Official is now works. build 1314 now we need to wait for CounterStrikeSharp update :)

**Comment by Ston3Cold** [comment]
> Official is now works. build 1314 now we need to wait for CounterStrikeSharp update :)

Version 267 of CSS was released 30 min ago, so I guess we're good to go :D

**Comment by zyhsck** [comment]
我的大部分插件无法使用，比如cs2kz
