### ISSUE TITLE
Metamod cant start (cs2WindowsServer)

### ISSUE THREAD

**Issue by ancientgodsse** [alliedmodders/metamod-source#197]
When start console just close,please help some one.I have installed Metamod:Source.stable build 1155
![45c77004-2712-4a0e-83be-3b6861f5417c (1)](https://github.com/user-attachments/assets/25319200-5947-4642-b2ad-5ac077ed67cb)

**Comment by M-archand** [comment]
Don't use stable, use Dev (2.x): https://www.sourcemm.net/downloads.php/?branch=master
