### ISSUE TITLE
Source 2 needs bins in linuxsteamrt64 instead of linux64

### ISSUE THREAD

**Issue by psychonic** [alliedmodders/metamod-source#39]
For Source 2, the binaries need to be available in addons/metamod/bin/linuxsteamrt64 instead of addons/metamod/bin/linux64 (how we currently ship).

I'm not sure how to best create a copy of them in AMBuild. The linux64 folder is still needed for Source 1 64-bit.

**Comment by peace-maker** [comment]
Fixed in #120
