### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Majkovsky** [alliedmodders/metamod-source#41]
**OS:**
Centos 7.3.1611

**Engine:**
CSGO

**SM & MM:S**
Sourcemod v1.8.0.6040
Metamod 1.10.7-**git961**

When I use ForceChangeLevel in the plugins or use changelevel in the server console:
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x7088DA48/0x00000810/0x'

It seems to me that the bug lies in the latest version of Metamod Build **961** and you have to go back to the previous old version **959**. Please fix problem newest version Metamod.

**Comment by peace-maker** [comment]
I'm assuming this to be fixed since there were no other reports and lots of csgo servers running MM:S in the last 5 years.
Please open a new issue if you're still experiencing problems on centos.
