### ISSUE TITLE
Accessing MM:S plugin through Lua Script in Dota

### ISSUE THREAD

**Issue by korroktheslavemaster** [alliedmodders/metamod-source#44]
I want to write a function in C++ which I can access through my custom game lua file (addon_game_mode.lua). Is this possible through MM:S ?

**Comment by psychonic** [comment]
For general help and assistance with using MM:S and writing MM:S plugins, please use the AlliedModders forums.

This tracker is for reporting and discussing bugs with MM:S itself.

**Comment by korroktheslavemaster** [comment]
Ah sorry. I'll do that.
