### ISSUE TITLE
Detected engine 8 but could not find GetVspBridge callback

### ISSUE THREAD

**Issue by Satanic-Spirit** [alliedmodders/metamod-source#58]
I just compiled latest dev release of metamod source code. These are the compile parameters.

`python ../configure.py --symbol-files --enable-optimize --sdks l4d2`
`ambuild`

When launching the server I got this back.

`Detected engine 8 but could not find GetVspBridge callback`

Just some follow up information.

`Debian GNU/Linux 9.9 (stretch)`
`gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)`

**Comment by KyleSanderson** [comment]
... what game?

**Comment by Satanic-Spirit** [comment]
I thought --sdks flag gave it away. It is **Left 4 Dead 2**

**Comment by vskwirblies** [comment]
I have the same issue.

**Comment by psychonic** [comment]
What if you compile with Clang instead of GCC? I believe there is a still a bug where certain parts don't link properly with GCC. It would usually manifest as a different error, but it could plausibly be that.

**Comment by vskwirblies** [comment]
I could not compile it with Clang - gave me compile errors. That's why I used GCC 6.5.0.

**Comment by psychonic** [comment]
Can you post the Clang version and/or the errors?

**Comment by vskwirblies** [comment]
Sure. 
Clang version:
clang version 3.9.1-19ubuntu1 (tags/RELEASE_391/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Compile errors:
![Screenshot from 2019-06-03 16-55-52](https://user-images.githubusercontent.com/26623941/58811820-ca24de00-8620-11e9-9204-76ae35693bc8.png)
This repeats a couple of times.

**Comment by psychonic** [comment]
Thanks. Should be an easy fix, and I think we’ve already done it on a couple of the other SDK branches. I’ll do it a bit later today.

**Comment by psychonic** [comment]
I added a fix for that warning now.

**Comment by vskwirblies** [comment]
Okay, great. Thanks :-)
So what am I supposed to git pull now? Is this an sdk issue so that I have to pull the newest version of the sdk? Or was it a fix in metamod?

**Comment by psychonic** [comment]
The SDK.
