### ISSUE TITLE
Fix GetCommandLineValue

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/metamod-source#61]
ICvar::GetCommandLineValue was removed in csgo.
https://github.com/alliedmodders/hl2sdk/pull/61
Problem code:
https://github.com/alliedmodders/metamod-source/blob/master/core/provider/provider_ep2.cpp#L322
We can replicate original GetCommandLineValue in provider. Original:
https://github.com/VSES/SourceEngine2007/blob/master/src_main/vstdlib/cvar.cpp#L461

My code version to pull in metamod master and 1.10
```cpp
const char *BaseProvider::GetCommandLineValue(const char *key, const char *defval)
{
	if (key[0] == '-' || key[0] == '+')
	{
		return CommandLine()->ParmValue(key, defval);
	}
#if SOURCE_ENGINE == SE_CSGO
	size_t len = strlen(key);
	char *search = new char[len + 2];
	search[0] = '+';
	memcpy(&search[1], key, len + 1);
	const char *value = CommandLine()->ParmValue(search, defval);
	delete[] search;
	return value;
#else
	else if (icvar)
	{
		const char *val;
		if ((val = icvar->GetCommandLineValue(key)) == NULL)
		{
			return defval;
		}

		return val;
	}

	return NULL;
#endif
}
```
And i noticed that function return NULL if no icvar interface, but i think it must to return defval in this case, isn't it? (bug?)

**Comment by agpmilli** [comment]
This change would be super useful for people having multiple servers running on the same CS:GO installation (with MM / SM).
Thanks in advance.
