### ISSUE TITLE
non-virtual destructor might cause undefined behavior

### ISSUE THREAD

**Issue by number201724** [alliedmodders/metamod-source#64]
error: deleting object of polymorphic class type ‘__SourceHook_FHCls_IServerGameDLLServerActivate0::CMyDelegateImpl’ which has non-virtual destructor might cause undefined behavior

../../../mmsource-1.10/core/sourcehook/sourcehook.h:1058:30:

**Comment by number201724** [comment]
`
	class ISHDelegate
	{
	public:
		virtual ~ISHDelegate() {}//missing this
		virtual bool IsEqual(ISHDelegate *pOtherDeleg) = 0;		// pOtherDeleg is from the same plugin and hookman
		virtual void DeleteThis() = 0;
	};
`

**Comment by SlidyBat** [comment]
I encountered the same error on another project after updating VS 2019, I suspect this warning/error was added to the /W4 level on VS 2019.

**Comment by number201724** [comment]
I encountered it when I compiled the extension on the WSL.

**Comment by dvander** [comment]
The error should be suppressed - -Wno-non-virtual-dtor, I believe. Feel free to submit a pull request.

Full explanation: We never use `delete` on an `ISHDelegate` pointer, it always gets cleaned up via `DeleteThis()`. Adding the virtual dtor would likely break ABI, so unless we can prove it's safe on all compilers it's a non-starter. Better to suppress the spurious warning.

**Comment by number201724** [comment]
If you don't use virtual dtor, there may be memory leaks, especially if the parent class deletes itself.

**Comment by dvander** [comment]
Please re-read comment my earlier comment. PRs (that do not break ABI) are welcome.

**Comment by number201724** [comment]
Okay, I got it.
