### ISSUE TITLE
Detected engine 21 but could not load...

### ISSUE THREAD

**Issue by XutaxKamay** [alliedmodders/metamod-source#65]
Hey there, I wanted to have fun with BMS lately, but unfortunately I get this error:
`L 04/20/2020 - 02:57:02: Detected engine 21 but could not load: /home/kamay/.steam/steam/steamapps/common/Black Mesa/bms/addons/metamod/bin/metamod.2.bms.so: undefined symbol: vec3_origin
`
I suppose that this commit (https://github.com/alliedmodders/metamod-source/commit/20c72b51e6df539a8ae91722c66084f) should have fixed it by linking mathlib but it didn't seem to be the case for some reasons I don't really know yet.

Thank you!

EDIT:
this is due to wrong tabulation I guess https://github.com/alliedmodders/metamod-source/blob/20c72b51e6df539a8ae91722c66084f56bc155f9/AMBuildScript#L329
EDIT EDIT:
after building myself, I have another issue with libtier0_srv.so probably that doesn't export KeyValuesSystem, I don't really know if it's due to my build/g++ version or anything.
Okay apparently it is exported by libvstdlib.so,

So I know why it doesn't find the libs, since metamod is based on dedicated servers, it uses _srv.so libraries, but since they're not loaded the symbols can't be found in a single player game (client),
It would be nice to allow people loading metamod in single player games.

It is not much an issue though I think.

What are you using to build on linux ? (somehow, libvstdlib.so doesn't get into the dependencies of the metamod module)

**Comment by asherkin** [comment]
You’ll want to use the stable branch - master has been updated for the Harmonious Prelude update which is not shipping a 32-bit Linux build (unless they’ve changed that since).

**Comment by XutaxKamay** [comment]
Thank you for your reply!

What would be a stable branch? Should I just checkout to a commit in particular I guess? (I mean I checked all the branches I did not see anything related to stable or I'm maybe blind)

Also I don't know why but I have to patch everytime the binary so it has the libvstdlib.so shared library as a dependency, I thought it was a problem with my configuration but apparently, with trying with multiples compilers and virtual machines, I can not get it.
Is there a particular way to build metamod with ambuild, like using steam runtime, using a specific gcc/g++ version or anything?

Because doing ```patchelf --add-needed libvstdlib.so package/addons/metamod/bin/metamod.2.bms.so``` always and I get compilation failures on some others sdks or different gcc/g++ versions.. I don't know.

Would you like to guide me in short terms?

Thank you

**Comment by asherkin** [comment]
Apologies, the stable branch is `1.10-dev`.

The linking failure might be caused by using GCC and the configuration of your distro, it's known to drop libraries when used by AMBuild on certain Linux distributions, try building with clang instead:

```
CC=clang CXX=clang++ ../configure.py -s bms --enable-optimize
```

**Comment by XutaxKamay** [comment]
Thank you for these precious information,
can I know which version of clang you're recommending? I've some issues during compilation.. (probably due to too recent version of clang)

**Comment by asherkin** [comment]
Clang 3.8 is used for the release builds.

**Comment by XutaxKamay** [comment]
Okay thank you a lot, I got it working. 
I'll remember all that. It would be really nice to say that you use clang-3.8 in this wiki https://wiki.alliedmods.net/Building_SourceMod

I could do it if you'd like, but I feel like it is not my right.
