### ISSUE TITLE
Detected engine 11 but could not load: /home/user/csgo/bin/libgcc_s.so.1: file too short

### ISSUE THREAD

**Issue by Ecklory** [alliedmodders/metamod-source#68]
https://github.com/alliedmodders/metamod-source/blob/988386eb293b27045192ba63a7de7ac9f6226550/loader/serverplugin.cpp#L167

There is a check for `libgcc_s.so.1` in the `/bin` directory. I suppose for compatibility.
How smart is it to use a system library? From the version that metamod will be built.

@psychonic

**Comment by peace-maker** [comment]
Sorry for the late reply. Which check are you referring to? That error sounds like a corrupted csgo server installation. You should delete the `bin/libgcc_s.so.1` file in your csgo install to have it use the system-wide version. This isn't related to what metamod was built against.
