### ISSUE TITLE
MetaMod doesn't appear to exist

### ISSUE THREAD

**Issue by VoxelTek** [alliedmodders/metamod-source#72]
Hi there,
So I have a Debian server machine running a TF2, HL2DM and SDK2013 server. These servers all work perfectly together, and I have never had issues in the past. However, recently I decided I wanted to install SourceMod. I discovered I would need MetaMod for this, so I got to work on installing that. I downloaded the latest stable Linux version, copied it over, and then had a /addons folder in my /tf2 folder. Everything was working perfectly. I started the server, and ran "meta version". However, I was greeted with "Unknown command "meta"". Does anyone know what could cause this? 

PS i also tried it with HL2DM. Same issue.

PPS i tried the VPK maker thing with both games, as well as the non-stable dev build with tf2. nothing changed.

**Comment by asherkin** [comment]
The common cause of this is installing the wrong version for the OS the server is running on.

Please could you run the `version`, `status`, and `plugin_print` commands in the server console while you think you have MM:S installed.

**Comment by VoxelTek** [comment]
![image](https://user-images.githubusercontent.com/53562267/92994677-b9f7f000-f53f-11ea-9580-c3d518027c7e.png)

**Comment by VoxelTek** [comment]
@asherkin hey sorry to bother you but i only have like a couple hours until i cant work on this anymore. any chance you could help?

**Comment by peace-maker** [comment]
Can you make sure the `addons` folder is next to the `cfg` folder and `gameinfo.txt` INSIDE the mod folder - not next to the `srcds_run` script?

**Comment by VoxelTek** [comment]
> 
> 
> Can you make sure the `addons` folder is next to the `cfg` folder and `gameinfo.txt` INSIDE the mod folder - not next to the `srcds_run` script?

unfortunately, the server broke. im waiting on a replacement machine that i can use. but until then, i cannot test this. sorry.

**Comment by VoxelTek** [comment]
> Can you make sure the `addons` folder is next to the `cfg` folder and `gameinfo.txt` INSIDE the mod folder - not next to the `srcds_run` script?

AHAHAHA THANK YOU SO MUCH IT WORKED
