### ISSUE TITLE
RE: Concerns of Malware still

### ISSUE THREAD

**Issue by Cazitron** [alliedmodders/metamod-source#74]
![image](https://user-images.githubusercontent.com/46332689/93005295-d08d4f80-f51d-11ea-8bca-23d285ebb1a9.png)

What does this mean then? When I tried to extract it into my server directory, this came up, again.

**Comment by asherkin** [comment]
It is still a false positive - "Malware-gen" is a generic detection. That said, `MMS_Installer.exe` is not part of the MM:S download (you appear to be downloading the source code archive) - make sure to get your builds from <https://metamodsource.net/downloads.php?branch=stable>.

Please don't open additional GitHub issues regarding this - you can still comment on closed issues, and this is a venue for bug reports and features requests only. You may be interested in visiting the AlliedModders [forum](https://forums.alliedmods.net/) or [Discord](https://discord.gg/HUc67zN).
