### ISSUE TITLE
Metamod is not shipping Linux64 Blade Symphony binaries

### ISSUE THREAD

**Issue by samzanemesis** [alliedmodders/metamod-source#76]
Hello
I work for Puny Human Games, we've worked with Alliedmodders before to bring support back to Blade Symphony in our new engine branch and it's working beautifully for x86 Windows (Thank you so much for the help!)

I have done some testing and I have not been able to get the same running on Linux, the latest Metamod build for Linux completely ommits binaries for Blade Symphony on any targets, the same for Sourcemod

Let me know what we can do on our end to help the team to achieve support for Linux64 for Blade

**Comment by asherkin** [comment]
Hi Sam, Unfortunately Blade Symphony is blazing a new trail here by being the only Source game to ship a 64-bit Linux SRCDS release, and the MM:S/SM ecosystem as a whole is a long way away from full 64-bit support on any platform. There are no first-party Valve titles that ship a 64-bit SRCDS at all, let alone as the only option, so it has mostly just been a curiosity up until recently.

A know a few people have been working on improving the 64-bit SRCDS support recently, testing with both Day of Infamy and Blade Symphony, so we may be able to start shipping something properly at some point - but it is probably some way off and there are a lot of large gaps (such as no 64-bit JIT for plugins).

Is it an option for you ship a 32-bit Linux build?
