### ISSUE TITLE
64-bit server.so fails to load on a Counter-Strike: Source server

### ISSUE THREAD

**Issue by BradleyMarie** [alliedmodders/metamod-source#79]
I've got a Counter-Strike: Source server packaged in a Docker container that has MetaMod:Source installed. I've got two Synology NAS on which I'm trying to get it up and running, a DS916+ and a DS620slim. Curiously, despite the same container being used on both devices, I get a crash every time I try to bring it up on the DS916+ while it comes up fine on the DS620slim.

The particular error I see when I try to bring it up on the DS916+ indicate that it's (incorrectly I believe) trying to load the 64-bit version of the Metamod binary instead of the 32-bit binary:

> failed to dlopen /opt/game/cstrike/../cstrike/addons/metamod/bin/linux64/server.so error=/opt/game/cstrike/../cstrike/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
> failed to dlopen /opt/game/hl2/../cstrike/addons/metamod/bin/linux64/server.so error=/opt/game/hl2/../cstrike/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
> failed to dlopen /opt/game/bin/../cstrike/addons/metamod/bin/linux64/server.so error=/opt/game/bin/../cstrike/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64

It's possible the issue is somehow triggered by the difference in kernel versions between the two devices--3.10.105 on the DS916+ vs. 4.4.59+ on the DS620slim--but I'm not sure what the exact mechanism would be if that's the case.

**Comment by asherkin** [comment]
The messages regarding the 64-bit binary failing to load are expected - the server will attempt to load both and only succeed on the correct one. If you check the startup messages of your working server you will see them there as well.

GitHub is not a good channel for general support, you should post full information about your issue (version numbers, full console output, any crash dumps, etc.) on the [AlliedModders Forum](https://forums.alliedmods.net/forumdisplay.php?f=58) or [Discord](https://discord.gg/HUc67zN).
