### ISSUE TITLE
Unable to load plugin "addons/metamod/bin/linux64/server"

### ISSUE THREAD

**Issue by mrdiega** [alliedmodders/metamod-source#80]
What is this error?

``` 
 failed to dlopen /home/serverarena/steamcmd/server/csgo/addons/metamod/bin/linux64/server.so error=/home/serverarena/steamcmd/server/csgo/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server" 
```

**Comment by asherkin** [comment]
That message is expected as part of SRCDS startup and not indicative of a problem.

**Comment by SugarD-x** [comment]
Is this the case with the Windows build too? I'm getting the same "unable to load plugin" there, except for Windows.

**Comment by dvander** [comment]
What agme?

**Comment by Headline** [comment]
> Is this the case with the Windows build too? I'm getting the same "unable to load plugin" there, except for Windows.

If metamod is otherwise functioning this error can be safely ignored

**Comment by SugarD-x** [comment]
> What game?

My apologies. Counter-Strike: Source.



> > Is this the case with the Windows build too? I'm getting the same "unable to load plugin" there, except for Windows.
> 
> If metamod is otherwise functioning this error can be safely ignored

It doesn't really make sense to me to ignore an _error_, though. I've never gotten this before until I updated MM today. Prior builds never displayed it, which has me concerned that something is broken.

**Comment by asherkin** [comment]
> I've never gotten this before until I updated MM today. Prior builds never displayed it, which has me concerned that something is broken.

64-bit support is new in MM:S.

**Comment by dvander** [comment]
There are 32-bit and 64-bit copies of MM:S in the same package to make distribution easier. srcds attempts to load both since it has no way to filter. One of them succeeds and one of them fails. As long as the "meta" command works, you're good. We have no control over this other than splitting our packages which would make distribution very complicated.

**Comment by TOWUK** [comment]
Who could solve this error?

**Comment by TOWUK** [comment]
![изображение](https://user-images.githubusercontent.com/28830162/133889495-22504036-5806-4ca8-a1b6-629a55317dcf.png)
