### ISSUE TITLE
Failed to open (the proper server.so for CSGO?) metamod.2.csgo.so?

### ISSUE THREAD

**Issue by KrillinsWorld** [alliedmodders/metamod-source#81]
We built a new server for our game servers (HP Proliant DL360p Gen8 with Debian 10.9) But for months this was noted in the server consoles for SM for god knows how long. It was noted this has to do with the 64bit class, but for CSGO there is its own file to load, yet somehow the file is not being called on. I just got the source, I will take a peek sometime, but something tells me it is not going to be that obvious, but to be unable to detect what engine is running seems to be a simple thing to do when one is a regular programmer? But the message below is seen in both CSGO and CSS server with MM:S.

```
 failed to dlopen /home/gameuser/servers/csgo_sh/csgo/addons/metamod/bin/linux64/server.so error=/home/gameuser/servers/csgo_sh/csgo/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"
```

At first I noticed the files were not there, so I staged them to the location for this CS:GO server. To my surprise there is a file in there JUST for CS:GO but it never calls it. To me this is an issue, as it seems CS:GO is really not getting the FULL function of MM:S as it should and may not be talking to SM properly either as it relies on the functions it is calling for to be there. Yet, the server still runs, but to me it seems to run a bit buggy with hit and misses mostly misses) causing me headaches for days on end. We look for error free servers, but this just depends on how good of a core we can build our servers on.

Best Regards,
Krillin

**Comment by dvander** [comment]
To make sure I understand correctly: is MM:S working, but printing an error message? or is it not working?

**Comment by Wend4r** [comment]
I just get this error output, but MM:S is works

**Comment by peace-maker** [comment]
SRCDS tries to load all plugins on start even the onces for a different architecture. The correct one is loaded and you can ignore the messages.
See #79 #80

**Comment by KrillinsWorld** [comment]
Sorry for the delay. I am resting up from fight with our new server this week. The dust has settled and I am back at tackling the smaller fires to put them out.

> Can you post the output of "plugin_print" in your server console?

plugin_printLoaded plugins:
---------------------
0:	"Metamod:Source 1.11.0-dev+1144"
---------------------
It appears to be working, but I am more concerned with functionality and reliability. Why would a plugin be throwing error messages if there weren't any "real" errors? That is why I am scratching my head. I do not ignore error messages, I tackle them, that is what I do.

If there is anything else you need from my servers, let me know.

Thanks,
Krillin

**Comment by asherkin** [comment]
SRCDS prints a lot of messages during normal operation that look like error messages, but they're not. This particular message is out of the control of MM:S.

**Comment by KrillinsWorld** [comment]
> To make sure I understand correctly: is MM:S working, but printing an error message? or is it not working?

It seems to work, but I am more concerned about functionality, compatibility and reliability. If the error is a false positive then I see other issues which causes a domino effect.

I looked at other issues posted, but I see nothing in relation to this issue as I checked before posting a new issue as the problems did not match, they were not identical. Trust me, I have better things to do then wast time.

But it appears the professionalism is not mutual.

Krillin

**Comment by KrillinsWorld** [comment]
Just got to love ignorance!

**Comment by KrillinsWorld** [comment]
> SRCDS prints a lot of messages during normal operation that look like error messages, but they're not. This particular message is out of the control of MM:S.

This is ignorance as this has everything to do with MM:S as this is where the message is coming from. But you close my case immaturely blowing off pointing the blame at something else unprofessional. As seen below and in first post!

`/home/gameuser/servers/csgo_sh/csgo/addons/metamod/bin/linux64/server.so`

Suite yourself!

**Comment by asherkin** [comment]
If you want to avoid the message you can remove the `metamod_x64.vdf` file from your addons directory, but you'll need to do it every time you update MM:S as both are included in the package for the convenience of people running 64-bit games. There are no side effects other than this message on start.
