### ISSUE TITLE
Metamod cannot interact with the engine

### ISSUE THREAD

**Issue by eldoradoel** [alliedmodders/metamod-source#82]
Thank for your contributions.
Due to today's CSGO update, Metamod cannot interact with the game.

**Comment by 1099255210** [comment]
Same problem. Hope it'll be recovered soon.

**Comment by wopox1337** [comment]
https://steamdb.info/patchnotes/6617586/ 

this update breaks metamod work

**Comment by ImDini** [comment]
Same here waiting for fix in order to get our servers back online

**Comment by ZUBAT** [comment]
I love Valve for such updates
Please fix this.

**Comment by eldoradoel** [comment]
CSGO have new update，metamod works normal
